version: '3.8'

services:
  # init-certs:
  #   build:
  #     context: ./init-certs
  #     dockerfile: Dockerfile
  #   volumes:
  #     - certs:/app/certs

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
      - ./backend/db.sqlite3:/app/db.sqlite3
      - ./certs:/app/certs:ro
    ports:
      - "8000:8000"
    depends_on:
      - vault
      # - init-certs

  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
      # - ./certs:/app/certs:ro
      # environment:
      # - VITE_API_URL=https://localhost
      # depends_on:
      # - init-certs

  vault:
    build:
      context: ./vault
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    volumes:
      - ./vault/config:/vault/config
      - ./vault/logs:/vault/logs:rw
      - ./vault/data:/vault/data:rw
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_TOKEN: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_ADDR: 'http://0.0.0.0:8200'
  # volumes:
  # certs:
