version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    depends_on:
      - vault

  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    volumes:
      - ./frontend:/app:delegated

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
      - vault

  vault:
    build:
      context: ./vault
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    volumes:
      - ./vault/config:/vault/config
      - ./vault/logs:/vault/logs:rw
      - ./vault/data:/vault/data:rw
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_TOKEN: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_ADDR: 'http://0.0.0.0:8200'
